name: Update Prayer Times

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 23 * * *'  # 8 AM EST

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: npm start

      - name: Commit Changes if Any
        run: |
          git config --global user.name "Prayer Bot"
          git config --global user.email "bot@rtpmuslimcommunity.space"
          git add .
          git diff --quiet || git commit -m "Auto update prayer times"
          git push
